version: '3.7'

networks:
  default:
    driver: bridge

services:
  keycloak:
    # docker run --name keycloak -p 8180:8180      -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin      quay.io/keycloak/keycloak:latest      start-dev      --http-port 8180      --http-relative-path /auth
    image: jboss/keycloak:15.0.2
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - '8180:8180'

  quickstart:
    build: .
    depends_on:
      - keycloak

